eco_dict = {
"A00":"Irregular Opening",
"A01":"Nimzowitsch–Larsen Attack",
"A02":"Bird Opening",
"A03":"Bird Opening, Lasker Gambit",
"A04":"Reti Opening",
"A05":"Reti Opening",
"A06":"Reti Opening",
"A07":"King's Indian Attack",
"A08":"King's Indian Attack",
"A09":"Reti Opening, Classical",
"A10":"English Opening",
"A11":"English Opening, Caro-Kann Defense",
"A12":"English Opening, Caro-Kann Defensive System",
"A13":"English Opening",
"A14":"English Opening",
"A15":"English Opening, Anglo-Indian Defense",
"A16":"English Opening",
"A17":"English Opening",
"A18":"English Opening",
"A19":"English Opening, Mikenas–Carls Variation",
"A20":"English Opening",
"A21":"English Opening",
"A22":"English Opening, Bremen System",
"A23":"English Opening, Bremen System",
"A24":"English Opening, Bremen System",
"A25":"English Opening, Sicilian Reversed",
"A26":"English Opening, Closed System",
"A27":"English Opening, Three Knights System",
"A28":"English Opening, Four Knights",
"A29":"English Opening, Four Knights Fianchetto",
"A30":"English Opening, Symmetrical",
"A31":"English Opening, Symmetrical",
"A32":"English Opening, Symmetrical",
"A33":"English Opening, Symmetrical",
"A34":"English Opening, Symmetrical",
"A35":"English Opening, Symmetrical",
"A36":"English Opening, Symmetrical",
"A37":"English Opening, Symmetrical",
"A38":"English Opening, Symmetrical, Botvinnik System",
"A39":"English Opening, Symmetrical",
"A40":"Queen's Pawn Opening",
"A41":"Old Indian Defense",
"A42":"Modern Defense",
"A43":"Old Benoni Defense",
"A44":"Old Benoni Defense",
"A45":"Queen's Pawn Game",
"A46":"Queen's Pawn Game, Torre Attack",
"A47":"Queen's Indian Defense",
"A48":"King's Indian Attack",
"A49":"King's Indian, Fianchetto without c4",
"A50":"Queen's Pawn Game",
"A51":"Budapest Gambit",
"A52":"Budapest Gambit Declined",
"A53":"Old Indian Defense",
"A54":"Old Indian Defense, Ukrainian Variation",
"A55":"Old Indian Defense",
"A56":"Benoni Defense",
"A57":"Benko Gambit",
"A58":"Benko Gambit, Fianchetto Variation",
"A59":"Benko Gambit, Main Line",
"A60":"Benoni Defense",
"A61":"Benoni Defense, Modern",
"A62":"Benoni Defense, Fianchetto Variation",
"A63":"Benoni Defense, Fianchetto",
"A64":"Benoni Defense, Modern Main Line",
"A65":"Benoni Defense, Four Pawns Attack",
"A66":"Benoni Defense, Pawn Storm",
"A67":"Benoni Defense, Taimanov Variation",
"A68":"Benoni Defense, Levy System",
"A69":"Benoni Defense, Classical",
"A70":"Benoni Defense, Classical, 7.f4",
"A71":"Benoni Defense, Classical",
"A72":"Benoni Defense, Classical",
"A73":"Benoni Defense, Classical",
"A74":"Benoni Defense, Classical",
"A75":"Benoni Defense, Classical",
"A76":"Benoni Defense, Classical",
"A77":"Benoni Defense, Classical",
"A78":"Benoni Defense, Classical",
"A79":"Benoni Defense, Classical",
"A80":"Dutch Defense",
"A81":"Dutch Defense, Leningrad",
"A82":"Dutch Defense, Staunton Gambit",
"A83":"Dutch Defense, Staunton Gambit",
"A84":"Dutch Defense",
"A85":"Dutch Defense, Rubinstein Variation",
"A86":"Dutch Defense, Classical",
"A87":"Dutch Defense, Leningrad Variation",
"A88":"Dutch Defense, Classical",
"A89":"Dutch Defense, Leningrad",
"A90":"Dutch Defense, Classical",
"A91":"Dutch Defense, Classical",
"A92":"Dutch Defense, Classical",
"A93":"Dutch Defense, Leningrad",
"A94":"Dutch Defense, Leningrad",
"A95":"Dutch Defense, Leningrad",
"A96":"Dutch Defense, Classical",
"A97":"Dutch Defense, Classical",
"A98":"Dutch Defense, Classical",
"A99":"Dutch Defense, Classical",





# B00–B09: Uncommon Semi-Open, Pirc, Modern, Alekhine, Owen, Hippopotamus
"B00":"Uncommon King's Pawn Opening",
"B01":"Scandinavian Defense",
"B02":"Alekhine Defense",
"B03":"Alekhine Defense, Four Pawns Attack",
"B04":"Alekhine Defense, Modern Variation",
"B05":"Alekhine Defense, Modern",
"B06":"Robatsch Defense (Modern Defense)",
"B07":"Pirc Defense",
"B08":"Pirc Defense, Classical",
"B09":"Pirc Defense, Austrian Attack",

# B10–B19: Caro-Kann Defense
"B10":"Caro-Kann Defense",
"B11":"Caro-Kann Defense, Two Knights",
"B12":"Caro-Kann Defense, Advance Variation",
"B13":"Caro-Kann Defense, Exchange Variation",
"B14":"Caro-Kann Defense, Panov–Botvinnik Attack",
"B15":"Caro-Kann Defense, Alekhine Gambit",
"B16":"Caro-Kann Defense, Bronstein–Larsen Variation",
"B17":"Caro-Kann Defense, Steinitz Variation",
"B18":"Caro-Kann Defense, Classical",
"B19":"Caro-Kann Defense, Classical, 11...Nd7",

# B20–B99: Sicilian Defense (all major sub-variations)
"B20":"Sicilian Defense",
"B21":"Sicilian Defense, Smith–Morra Gambit",
"B22":"Sicilian Defense, Alapin Variation",
"B23":"Sicilian Defense, Closed",
"B24":"Sicilian Defense, Closed, 6.Be3",
"B25":"Sicilian Defense, Closed, 6.Be2",
"B26":"Sicilian Defense, Closed, 6.f4",
"B27":"Sicilian Defense, Hungarian",
"B28":"Sicilian Defense, O’Kelly Variation",
"B29":"Sicilian Defense, Nimzowitsch Variation",

# B30–B39: Sicilian (Rossolimo / Moscow / Closed)
"B30":"Sicilian Defense",
"B31":"Sicilian Defense, Nimzo Variation",
"B32":"Sicilian Defense, Labourdonnais–Loewenthal",
"B33":"Sicilian Defense, Scheveningen Variation",
"B34":"Sicilian Defense, Accelerated Dragon",
"B35":"Sicilian Defense, Accelerated Dragon, Modern",
"B36":"Sicilian Defense, Accelerated Dragon, Maroczy Bind",
"B37":"Sicilian Defense, Accelerated Dragon, Maroczy Bind",
"B38":"Sicilian Defense, Accelerated Dragon",
"B39":"Sicilian Defense, Accelerated Dragon",

# B40–B49: Sicilian (Taimanov, Kan, Paulsen)
"B40":"Sicilian Defense",
"B41":"Sicilian Defense, Paulsen Variation",
"B42":"Sicilian Defense, Paulsen, Kan",
"B43":"Sicilian Defense, Kan Variation",
"B44":"Sicilian Defense, Taimanov",
"B45":"Sicilian Defense, Taimanov, 5.Nc3",
"B46":"Sicilian Defense, Taimanov, 6.Be3",
"B47":"Sicilian Defense, Taimanov, 7.Qf3",
"B48":"Sicilian Defense, Taimanov, 8.O-O",
"B49":"Sicilian Defense, Taimanov, 8…Be7",

# B50–B59: Sicilian (Classical)
"B50":"Sicilian Defense",
"B51":"Sicilian Defense, Richter–Rauzer",
"B52":"Sicilian Defense, Richter–Rauzer",
"B53":"Sicilian Defense, Chekhover Variation",
"B54":"Sicilian Defense, Paulsen",
"B55":"Sicilian Defense, Paulsen",
"B56":"Sicilian Defense, Boleslavsky",
"B57":"Sicilian Defense, Sozin Attack",
"B58":"Sicilian Defense, Boleslavsky System",
"B59":"Sicilian Defense, Boleslavsky",

# B60–B69: Sicilian Scheveningen
"B60":"Sicilian Defense, Richter–Rauzer Attack",
"B61":"Sicilian Defense, Richter–Rauzer, 6.Bg5",
"B62":"Sicilian Defense, Richter–Rauzer, 7.Qd2",
"B63":"Sicilian Defense, Richter–Rauzer, 7…Qc7",
"B64":"Sicilian Defense, Richter–Rauzer, Classical",
"B65":"Sicilian Defense, Richter–Rauzer Attack",
"B66":"Sicilian Defense, Richter–Rauzer, 7…a6",
"B67":"Sicilian Defense, Richter–Rauzer, 7…Nc6",
"B68":"Sicilian Defense, Richter–Rauzer, 9…Be7",
"B69":"Sicilian Defense, Richter–Rauzer, 9…Nxd4",

# B70–B79: Sicilian Dragon
"B70":"Sicilian Defense, Dragon Variation",
"B71":"Sicilian Defense, Levenfish Attack",
"B72":"Sicilian Defense, Dragon, 6.Be3",
"B73":"Sicilian Defense, Dragon, Classical",
"B74":"Sicilian Defense, Dragon, Yugoslav Attack",
"B75":"Sicilian Defense, Dragon, Yugoslav Attack 9.Bc4",
"B76":"Sicilian Defense, Dragon, Yugoslav 10.O-O-O",
"B77":"Sicilian Defense, Dragon, Yugoslav 12.h4",
"B78":"Sicilian Defense, Dragon, Yugoslav 13.h5",
"B79":"Sicilian Defense, Dragon, Soltis Variation",

# B80–B99: Sicilian Najdorf (sharpest)
"B80":"Sicilian Defense, Scheveningen",
"B81":"Sicilian Defense, Scheveningen, Keres Attack",
"B82":"Sicilian Defense, Scheveningen",
"B83":"Sicilian Defense, Scheveningen, Nd7",
"B84":"Sicilian Defense, Scheveningen",
"B85":"Sicilian Defense, Scheveningen, Classical",
"B86":"Sicilian Defense, Sozin Attack",
"B87":"Sicilian Defense, Sozin, 7.Be3",
"B88":"Sicilian Defense, Sozin, 7…Be7",
"B89":"Sicilian Defense, Sozin, Fischer–Sozin Attack",
"B90":"Sicilian Defense, Najdorf",
"B91":"Sicilian Defense, Najdorf, Zagreb Variation",
"B92":"Sicilian Defense, Najdorf, Opocensky",
"B93":"Sicilian Defense, Najdorf, 6.f4",
"B94":"Sicilian Defense, Najdorf, 6.Bg5",
"B95":"Sicilian Defense, Najdorf, 6…e6",
"B96":"Sicilian Defense, Najdorf, 6…Bg4",
"B97":"Sicilian Defense, Najdorf, Poisoned Pawn",
"B98":"Sicilian Defense, Najdorf, 7.f4",
"B99":"Sicilian Defense, Najdorf, 7…Be7",




# C00–C19: French Defense
"C00":"French Defense",
"C01":"French Defense, Exchange Variation",
"C02":"French Defense, Advance Variation",
"C03":"French Defense, Tarrasch Variation",
"C04":"French Defense, Tarrasch, Guimard Variation",
"C05":"French Defense, Tarrasch",
"C06":"French Defense, Tarrasch, Closed",
"C07":"French Defense, Tarrasch, Open",
"C08":"French Defense, Tarrasch, Open",
"C09":"French Defense, Tarrasch, Open",
"C10":"French Defense, Rubinstein Variation",
"C11":"French Defense, Steinitz Variation",
"C12":"French Defense, MacCutcheon Variation",
"C13":"French Defense, Classical",
"C14":"French Defense, Classical",
"C15":"French Defense, Winawer Variation",
"C16":"French Defense, Winawer",
"C17":"French Defense, Winawer",
"C18":"French Defense, Winawer",
"C19":"French Defense, Winawer, Advance Variation",

# C20–C29: King’s Pawn Opening / King's Gambit
"C20":"King's Pawn Game",
"C21":"Center Game",
"C22":"Center Game, Danish Gambit",
"C23":"Bishop's Opening",
"C24":"Bishop’s Opening, Berlin Defense",
"C25":"Vienna Game",
"C26":"Vienna Game, Falkbeer Variation",
"C27":"Vienna Game, Vienna Gambit",
"C28":"Vienna Game, Vienna Gambit",
"C29":"Vienna Gambit, Steinitz Variation",

# C30–C39: King’s Gambit
"C30":"King’s Gambit",
"C31":"King’s Gambit Declined",
"C32":"King’s Gambit Declined, Falkbeer Countergambit",
"C33":"King’s Gambit Accepted",
"C34":"King’s Gambit Accepted, Becker Defense",
"C35":"King’s Gambit Accepted, Cunningham Defense",
"C36":"King’s Gambit Accepted, Abbazia Defense",
"C37":"King’s Gambit Accepted, Muzio Gambit",
"C38":"King’s Gambit Accepted, Hanstein Gambit",
"C39":"King’s Gambit Accepted, Allgaier Gambit",

# C40–C49: King’s Knight Opening / Four Knights / Scotch
"C40":"King’s Knight Opening",
"C41":"Philidor Defense",
"C42":"Petrov’s Defense",
"C43":"Petrov’s Defense, Modern Attack",
"C44":"King’s Pawn Game",
"C45":"Scotch Game",
"C46":"Three Knights / Four Knights Hybrid",
"C47":"Four Knights Game",
"C48":"Four Knights, Spanish Variation",
"C49":"Four Knights, Double Ruy Lopez",

# C50–C59: Italian Game, Giuoco Piano, Evans Gambit
"C50":"Italian Game",
"C51":"Evans Gambit",
"C52":"Evans Gambit, Pierce Defense",
"C53":"Giuoco Piano, Moeller Attack",
"C54":"Giuoco Piano",
"C55":"Two Knights Defense",
"C56":"Two Knights Defense, Ulvestad Variation",
"C57":"Two Knights Defense, Fegatello Attack",
"C58":"Two Knights Defense, Fried Liver Attack",
"C59":"Two Knights Defense, Ponziani Gambit",

# C60–C99: Ruy Lopez (Spanish Opening)
"C60":"Ruy Lopez",
"C61":"Ruy Lopez, Bird Defense",
"C62":"Ruy Lopez, Old Steinitz Defense",
"C63":"Ruy Lopez, Schliemann Defense",
"C64":"Ruy Lopez, Classical",
"C65":"Ruy Lopez, Berlin Defense",
"C66":"Ruy Lopez, Berlin Defense, Classical Variation",
"C67":"Ruy Lopez, Berlin Defense, Mortimer Trap",
"C68":"Ruy Lopez, Exchange Variation",
"C69":"Ruy Lopez, Exchange Variation, Gligoric",
"C70":"Ruy Lopez, Morphy Defense",
"C71":"Ruy Lopez, Modern Steinitz Defense",
"C72":"Ruy Lopez, Modern Steinitz Defense, 5.O-O",
"C73":"Ruy Lopez, Modern Steinitz Defense, 6.dxe5",
"C74":"Ruy Lopez, Modern Steinitz Defense, Fianchetto",
"C75":"Ruy Lopez, Modern Steinitz Defense, 6...Be7",
"C76":"Ruy Lopez, Modern Steinitz Defense, 7.Re1",
"C77":"Ruy Lopez, Anderssen Variation",
"C78":"Ruy Lopez, Archangelsk",
"C79":"Ruy Lopez, Archangelsk / Modern",
"C80":"Ruy Lopez, Open Variation",
"C81":"Ruy Lopez, Open Variation, Howell Attack",
"C82":"Ruy Lopez, Open Variation, 9.Nbd2",
"C83":"Ruy Lopez, Open Variation, 9.Be3",
"C84":"Ruy Lopez, Closed",
"C85":"Ruy Lopez, Exchange Variation",
"C86":"Ruy Lopez, Worrall Attack",
"C87":"Ruy Lopez, Closed",
"C88":"Ruy Lopez, Closed, Anti-Marshall",
"C89":"Ruy Lopez, Marshall Gambit",
"C90":"Ruy Lopez, Closed",
"C91":"Ruy Lopez, Closed, 7...d6",
"C92":"Ruy Lopez, Closed, 8.d4",
"C93":"Ruy Lopez, Closed, Smyslov Defense",
"C94":"Ruy Lopez, Closed, Breyer",
"C95":"Ruy Lopez, Closed, Breyer",
"C96":"Ruy Lopez, Closed, 9.h3",
"C97":"Ruy Lopez, Closed, Chigorin Defense",
"C98":"Ruy Lopez, Closed, Chigorin",
"C99":"Ruy Lopez, Closed, Chigorin, 12...d5",



# D00–D09: Queen’s Pawn Games (Non-Gambit)
"D00":"Queen’s Pawn Game",
"D01":"Richter–Veresov Attack",
"D02":"Queen’s Pawn Game, London System",
"D03":"Torre Attack",
"D04":"Queen’s Pawn Game, Colle System",
"D05":"Queen’s Pawn Game, Zukertort Variation",
"D06":"Queen’s Gambit Declined",
"D07":"Queen’s Gambit Declined, Chigorin Defense",
"D08":"Queen’s Gambit Declined, Albin Countergambit",
"D09":"Queen’s Gambit Declined, Albin, 5.g3",

# D10–D19: Slav Defense
"D10":"Slav Defense",
"D11":"Slav Defense, 3.Nf3",
"D12":"Slav Defense, 4.e3",
"D13":"Slav Defense, Exchange Variation",
"D14":"Slav Defense, Exchange, Schallopp Variation",
"D15":"Slav Defense, Schlechter Variation",
"D16":"Slav Defense, Classical",
"D17":"Slav Defense, Dutch Variation",
"D18":"Slav Defense, Dutch, 6.Ne5",
"D19":"Slav Defense, Czech Variation",

# D20–D29: Queen’s Gambit Accepted
"D20":"Queen’s Gambit Accepted",
"D21":"Queen’s Gambit Accepted, 3.Nf3",
"D22":"Queen’s Gambit Accepted, 4.e3",
"D23":"Queen’s Gambit Accepted, Mannheim Variation",
"D24":"Queen’s Gambit Accepted, Classical",
"D25":"Queen’s Gambit Accepted, 5.e3",
"D26":"Queen’s Gambit Accepted, 6.Qc2",
"D27":"Queen’s Gambit Accepted, Rubinstein",
"D28":"Queen’s Gambit Accepted, Rubinstein, 7.Bd3",
"D29":"Queen’s Gambit Accepted, Classical Main Line",

# D30–D39: Queen’s Gambit Declined (Orthodox)
"D30":"Queen’s Gambit Declined",
"D31":"Queen’s Gambit Declined, Semi-Slav Attempt",
"D32":"Queen’s Gambit Declined, Tarrasch Defense",
"D33":"Queen’s Gambit Declined, Tarrasch, 4...c5",
"D34":"Queen’s Gambit Declined, Vienna Variation",
"D35":"Queen’s Gambit Declined, Exchange Variation",
"D36":"QGD, Exchange, Positional Line",
"D37":"QGD, Exchange, Classical",
"D38":"QGD, Ragozin Variation",
"D39":"QGD, Ragozin, 6...b5 Gambit",

# D40–D49: Queen’s Gambit Declined (Semi-Tarrasch, Semi-Slav)
"D40":"QGD, Semi-Tarrasch Defense",
"D41":"QGD, Semi-Tarrasch, 5.e3",
"D42":"QGD, Semi-Tarrasch, 5.cxd5",
"D43":"Semi-Slav Defense",
"D44":"Semi-Slav Defense, Botvinnik System",
"D45":"Semi-Slav, Anti-Meran",
"D46":"Semi-Slav, Meran Variation",
"D47":"Semi-Slav, Meran, 8...a6",
"D48":"Semi-Slav, Meran, 8...Bb7",
"D49":"Semi-Slav, Meran, Rabinovich",

# D50–D59: Queen’s Gambit Declined (Tartakower, Lasker, Cambridge Springs)
"D50":"QGD",
"D51":"QGD, 5.Bf4",
"D52":"QGD, Cambridge Springs Defense",
"D53":"QGD, Lasker Defense",
"D54":"QGD, Anti-Tartakower",
"D55":"QGD, Tartakower Defense",
"D56":"QGD, Tartakower, 7...b6",
"D57":"QGD, Tartakower, Main Line",
"D58":"QGD, Tartakower, Revision",
"D59":"QGD, Tartakower, Gligoric",

# D60–D69: Ragozin / Vienna / Neo-Grunfeld
"D60":"QGD, Ragozin Defense",
"D61":"QGD, Orthodox Defense",
"D62":"QGD, Orthodox, Rubinstein Variation",
"D63":"QGD, Orthodox, Rubinstein",
"D64":"Orthodox Defense, Rubinstein, 7.Qc2",
"D65":"Orthodox Defense, Rubinstein, 8.e3",
"D66":"Orthodox Defense, Classical",
"D67":"Orthodox Defense, Classical",
"D68":"Orthodox Defense, Classical, 13.Ne5",
"D69":"Neo-Grunfeld Defense",

# D70–D99: Grunfeld Defense, Catalan
"D70":"Neo-Grunfeld Defense",
"D71":"Grunfeld Defense",
"D72":"Grunfeld Defense, Russian Variation",
"D73":"Grunfeld Defense, Semislav, 5.cxd5",
"D74":"Grunfeld Defense, Smyslov Variation",
"D75":"Grunfeld Defense, Classical",
"D76":"Grunfeld Defense, Exchange Variation",
"D77":"Grunfeld Defense, Exchange, 7.Nf3",
"D78":"Grunfeld Defense, Exchange, 8.Rb1",
"D79":"Grunfeld Defense, Exchange, 8.Be3",
"D80":"Grunfeld Defense, Stockholm",
"D81":"Grunfeld Defense, Stockholm, 7.Be3",
"D82":"Grunfeld Defense, 7.Nf3",
"D83":"Grunfeld Defense, Grigoriev Variation",
"D84":"Grunfeld Defense, 7.Be2",
"D85":"Grunfeld Defense, 7.Bc4",
"D86":"Grunfeld Defense, Exchange, Simagin Variation",
"D87":"Grunfeld Defense, Exchange, Spassky Variation",
"D88":"Grunfeld Defense, Sämisch",
"D89":"Grunfeld Defense, Sämisch, Early h4",
"D90":"Grunfeld Defense, Three Knights",
"D91":"Grunfeld Defense, Three Knights, 5.Bg5",
"D92":"Grunfeld Defense, Three Knights, 6.Bxf6",
"D93":"Grunfeld Defense, Fianchetto",
"D94":"Grunfeld Defense, Three Knights, 7.e4",
"D95":"Grunfeld Defense, 7...c5",
"D96":"Grunfeld Defense, Russian Variation",
"D97":"Grunfeld Defense, Russian, 7...Nc6",
"D98":"Grunfeld Defense, Russian, 8.Rb1",
"D99":"Grunfeld Defense, Russian, 8.Be3",




# E00–E09: Catalan / Closed Games
"E00": "Catalan Opening",
"E01": "Catalan, Closed",
"E02": "Catalan, Closed, 5.Nf3",
"E03": "Catalan, Closed, 6.Nc3",
"E04": "Catalan, Open",
"E05": "Catalan, Open, Classical",
"E06": "Catalan, Closed, Botvinnik Variation",
"E07": "Catalan, Closed, 7.Qc2",
"E08": "Catalan, Closed, 7.Qc2 Bd7",
"E09": "Catalan, Closed, 8.a4",

# E10–E19: Queen’s Indian Defense
"E10": "Queen’s Indian Defense",
"E11": "Queen’s Indian, 4.g3",
"E12": "Queen’s Indian, Petrosian Variation",
"E13": "Queen’s Indian, Petrosian, 6.b3",
"E14": "Queen’s Indian, Main Line",
"E15": "Queen’s Indian, Nimzowitsch Variation",
"E16": "Queen’s Indian, Capablanca Variation",
"E17": "Queen’s Indian, Traditional Line",
"E18": "Queen’s Indian, Old Main Line",
"E19": "Queen’s Indian, Classical Variation",

# E20–E59: Nimzo-Indian Defense
"E20": "Nimzo-Indian Defense",
"E21": "Nimzo-Indian, Three Knights",
"E22": "Nimzo-Indian, Three Knights, 4.Qc2",
"E23": "Nimzo-Indian, Three Knights, 4.e3",
"E24": "Nimzo-Indian, Three Knights, 4.Nf3",
"E25": "Nimzo-Indian, Saemisch Variation",
"E26": "Nimzo-Indian, Saemisch, 5.Nf3",
"E27": "Nimzo-Indian, Saemisch, 6.Nf3",
"E28": "Nimzo-Indian, Classical",
"E29": "Nimzo-Indian, Classical, 4.Qc2",
"E30": "Nimzo-Indian, Leningrad Variation",
"E31": "Nimzo-Indian, Leningrad, 5.Bg5",
"E32": "Nimzo-Indian, Classical Variation, 4.Qc2",
"E33": "Nimzo-Indian, Classical, 4...Nc6",
"E34": "Nimzo-Indian, Classical, Rubinstein",
"E35": "Nimzo-Indian, Classical, 4...b6",
"E36": "Nimzo-Indian, Classical, Hübner",
"E37": "Nimzo-Indian, Classical, 4.Qc2 O-O",
"E38": "Nimzo-Indian, Classical, 4.Qc2 c5",
"E39": "Nimzo-Indian, Classical, 4.Qc2 Bb7",
"E40": "Nimzo-Indian, 4.e3",
"E41": "Nimzo-Indian, 4...c5",
"E42": "Nimzo-Indian, 4.e3 O-O",
"E43": "Nimzo-Indian, Fischer Variation",
"E44": "Nimzo-Indian, Fischer, 5.Ne2",
"E45": "Nimzo-Indian, 4.e3 O-O, 5.Nf3",
"E46": "Nimzo-Indian, 4.e3 O-O, 6.Bd3",
"E47": "Nimzo-Indian, 4.e3 O-O, 7.O-O",
"E48": "Nimzo-Indian, 4.e3 O-O, 7...d5",
"E49": "Nimzo-Indian, 4.e3 O-O, 8.cxd5",
"E50": "Nimzo-Indian, 4.e3 O-O, 8...exd5",
"E51": "Nimzo-Indian, 4.e3 O-O, 9.Nf3",
"E52": "Nimzo-Indian, 4.e3 O-O, 10...Nc6",
"E53": "Nimzo-Indian, 4.e3 O-O, 11...Re8",
"E54": "Nimzo-Indian, 4.e3 O-O, Gligoric System",
"E55": "Nimzo-Indian, 4.e3 O-O, 8...dxc4",
"E56": "Nimzo-Indian, 4.e3 O-O, Rubinstein System",
"E57": "Nimzo-Indian, 4.e3 O-O, 9...cxd4",
"E58": "Nimzo-Indian, 4.e3 O-O, 8...b6",
"E59": "Nimzo-Indian, 4.e3 O-O, Main Line",

# E60–E99: King’s Indian Defense & Benoni
"E60": "King’s Indian Defense",
"E61": "KID, Smyslov System",
"E62": "KID, Fianchetto",
"E63": "KID, Fianchetto, Panno",
"E64": "KID, Fianchetto, Yugoslav System",
"E65": "KID, Fianchetto, Yugoslav Panno",
"E66": "KID, Fianchetto, Yugoslav, 7...Nc6",
"E67": "KID, Fianchetto, Yugoslav, 8.Rb1",
"E68": "KID, Fianchetto, Yugoslav, 9...Rb8",
"E69": "KID, Fianchetto, Yugoslav Main Line",
"E70": "KID, 5.Nf3",
"E71": "KID, Makagonov System",
"E72": "KID, 5.Nf3, 6.h3",
"E73": "KID, Averbakh System",
"E74": "KID, Averbakh, 6...c5",
"E75": "KID, Averbakh, 7.d5",
"E76": "KID, Four Pawns Attack",
"E77": "KID, Four Pawns, 6.Be2",
"E78": "KID, Four Pawns, Main Line",
"E79": "KID, Four Pawns, Dynamic Line",
"E80": "KID, Sämisch Variation",
"E81": "KID, Sämisch, 5.Nge2",
"E82": "KID, Sämisch, 6.Be3",
"E83": "KID, Sämisch, 6...c5",
"E84": "KID, Sämisch, Panno",
"E85": "KID, Sämisch, Orthodox",
"E86": "KID, Sämisch, Orthodox, 7...c6",
"E87": "KID, Sämisch, Orthodox Main Line",
"E88": "KID, Sämisch, Closed Variation",
"E89": "KID, Sämisch, Closed Main Line",
"E90": "KID, 6.Be2",
"E91": "KID, Classical",
"E92": "KID, Classical, 7.O-O",
"E93": "KID, Classical, Main Line",
"E94": "KID, Classical, 7...Na6",
"E95": "KID, Classical, 8.Re1",
"E96": "KID, Classical, 8.Re1 Nd7",
"E97": "KID, Classical, Orthodox",
"E98": "KID, Classical, Mar del Plata",
"E99": "KID, Classical, Mar del Plata Main Line"

};

